//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TellOP.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TellOP.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2016 University of Murcia
        ///
        ///This software is supported by the Erasmus+ Programme of the European Union: TELL-OP - Transforming European Learner Language into Learning Opportunities A KA200 Higher Education Strategic Partnership 2014‐1‐ES01‐KA203-004782..
        /// </summary>
        public static string About_CopyrightNotice {
            get {
                return ResourceManager.GetString("About_CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View third-party licenses.
        /// </summary>
        public static string About_ThirdPartyLicenses {
            get {
                return ResourceManager.GetString("About_ThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the third-party license notices..
        /// </summary>
        public static string About_ThirdPartyLicenses_UnableToLoad {
            get {
                return ResourceManager.GetString("About_ThirdPartyLicenses_UnableToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party licenses.
        /// </summary>
        public static string About_ThirdPartyLicensesTitle {
            get {
                return ResourceManager.GetString("About_ThirdPartyLicensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Tell-OP.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving your profile data from the server. Please try again..
        /// </summary>
        public static string API_UserDataError {
            get {
                return ResourceManager.GetString("API_UserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile data retrieval error.
        /// </summary>
        public static string API_UserDataErrorTitle {
            get {
                return ResourceManager.GetString("API_UserDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading your profile data retrieved from the server. Please try again..
        /// </summary>
        public static string API_UserDataJSONError {
            get {
                return ResourceManager.GetString("API_UserDataJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile data retrieval error.
        /// </summary>
        public static string API_UserDataJSONErrorTitle {
            get {
                return ResourceManager.GetString("API_UserDataJSONErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2016 University of Murcia
        ///
        ///Developed by Mattia Zago and Alessandro Menti.
        /// </summary>
        public static string AppCredits {
            get {
                return ResourceManager.GetString("AppCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell-OP.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        public static string BulletPoint {
            get {
                return ResourceManager.GetString("BulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string ButtonHide {
            get {
                return ResourceManager.GetString("ButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ButtonProfile {
            get {
                return ResourceManager.GetString("ButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and override.
        /// </summary>
        public static string ButtonSaveAndOverride {
            get {
                return ResourceManager.GetString("ButtonSaveAndOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string CollinsViewCell_Definition {
            get {
                return ResourceManager.GetString("CollinsViewCell_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Collins.
        /// </summary>
        public static string CollinsViewCell_DictionaryName_Contracted {
            get {
                return ResourceManager.GetString("CollinsViewCell_DictionaryName_Contracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Collins.
        /// </summary>
        public static string CollinsViewCell_DictionaryName_Expanded {
            get {
                return ResourceManager.GetString("CollinsViewCell_DictionaryName_Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string CollinsViewCell_Example {
            get {
                return ResourceManager.GetString("CollinsViewCell_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related words.
        /// </summary>
        public static string CollinsViewCell_Related {
            get {
                return ResourceManager.GetString("CollinsViewCell_Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also.
        /// </summary>
        public static string CollinsViewCell_SeeAlso {
            get {
                return ResourceManager.GetString("CollinsViewCell_SeeAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sense {0}.
        /// </summary>
        public static string CollinsViewCell_SenseCounter {
            get {
                return ResourceManager.GetString("CollinsViewCell_SenseCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable WiFi or mobile data and try again..
        /// </summary>
        public static string ConnectivityMissing_Text {
            get {
                return ResourceManager.GetString("ConnectivityMissing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the Internet.
        /// </summary>
        public static string ConnectivityMissing_Title {
            get {
                return ResourceManager.GetString("ConnectivityMissing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile page will be added soon.
        /// </summary>
        public static string Dashboard_ProfileAddedSoon {
            get {
                return ResourceManager.GetString("Dashboard_ProfileAddedSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Settings page will be added soon.
        /// </summary>
        public static string Dashboard_SettingsAddedSoon {
            get {
                return ResourceManager.GetString("Dashboard_SettingsAddedSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the data. Press the Refresh button to try again..
        /// </summary>
        public static string Dashboard_TabError {
            get {
                return ResourceManager.GetString("Dashboard_TabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Dashboard_TabFeatured {
            get {
                return ResourceManager.GetString("Dashboard_TabFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see the details of an exercise, select it from the list below..
        /// </summary>
        public static string Dashboard_TabFeatured_Description {
            get {
                return ResourceManager.GetString("Dashboard_TabFeatured_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no featured exercises at this time..
        /// </summary>
        public static string Dashboard_TabFeatured_Description_NoFeatured {
            get {
                return ResourceManager.GetString("Dashboard_TabFeatured_Description_NoFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured exercises.
        /// </summary>
        public static string Dashboard_TabFeatured_Title {
            get {
                return ResourceManager.GetString("Dashboard_TabFeatured_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Dashboard_TabHistory {
            get {
                return ResourceManager.GetString("Dashboard_TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can access all exercises you already submitted from this page..
        /// </summary>
        public static string Dashboard_TabHistory_Description {
            get {
                return ResourceManager.GetString("Dashboard_TabHistory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not submitted any exercises so far..
        /// </summary>
        public static string Dashboard_TabHistory_Description_NoHistory {
            get {
                return ResourceManager.GetString("Dashboard_TabHistory_Description_NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted exercises.
        /// </summary>
        public static string Dashboard_TabHistory_Title {
            get {
                return ResourceManager.GetString("Dashboard_TabHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Dashboard_TabStats {
            get {
                return ResourceManager.GetString("Dashboard_TabStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write an essay between {0} and {1} words..
        /// </summary>
        public static string EssayExercise_MinMaxWords {
            get {
                return ResourceManager.GetString("EssayExercise_MinMaxWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adj..
        /// </summary>
        public static string EssayExerciseView_Adjectives {
            get {
                return ResourceManager.GetString("EssayExerciseView_Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adv..
        /// </summary>
        public static string EssayExerciseView_Adverbs {
            get {
                return ResourceManager.GetString("EssayExerciseView_Adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string EssayExerciseView_Analysis {
            get {
                return ResourceManager.GetString("EssayExerciseView_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exercise doesn&apos;t have any preliminary text..
        /// </summary>
        public static string EssayExerciseView_ExSupportTextContentError {
            get {
                return ResourceManager.GetString("EssayExerciseView_ExSupportTextContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Text.
        /// </summary>
        public static string EssayExerciseView_ExSupportTextLabel {
            get {
                return ResourceManager.GetString("EssayExerciseView_ExSupportTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string EssayExerciseView_Load {
            get {
                return ResourceManager.GetString("EssayExerciseView_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouns.
        /// </summary>
        public static string EssayExerciseView_Nouns {
            get {
                return ResourceManager.GetString("EssayExerciseView_Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep..
        /// </summary>
        public static string EssayExerciseView_Preposition {
            get {
                return ResourceManager.GetString("EssayExerciseView_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string EssayExerciseView_Reset {
            get {
                return ResourceManager.GetString("EssayExerciseView_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset the current exercise content?.
        /// </summary>
        public static string EssayExerciseView_ResetAlertMessage {
            get {
                return ResourceManager.GetString("EssayExerciseView_ResetAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the current exercise.
        /// </summary>
        public static string EssayExerciseView_ResetAlertTitle {
            get {
                return ResourceManager.GetString("EssayExerciseView_ResetAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string EssayExerciseView_Search {
            get {
                return ResourceManager.GetString("EssayExerciseView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show text.
        /// </summary>
        public static string EssayExerciseView_ShowText {
            get {
                return ResourceManager.GetString("EssayExerciseView_ShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string EssayExerciseView_Submit {
            get {
                return ResourceManager.GetString("EssayExerciseView_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string EssayExerciseView_Title {
            get {
                return ResourceManager.GetString("EssayExerciseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncl..
        /// </summary>
        public static string EssayExerciseView_Unclassified {
            get {
                return ResourceManager.GetString("EssayExerciseView_Unclassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbs.
        /// </summary>
        public static string EssayExerciseView_Verbs {
            get {
                return ResourceManager.GetString("EssayExerciseView_Verbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted..
        /// </summary>
        public static string EssayExerciseViewAnalysisAborted {
            get {
                return ResourceManager.GetString("EssayExerciseViewAnalysisAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another analysis is running. Please wait until the current analysis is finished..
        /// </summary>
        public static string EssayExerciseViewAnalyzeTextExceptionAnotherAnalysisIsRunning {
            get {
                return ResourceManager.GetString("EssayExerciseViewAnalyzeTextExceptionAnotherAnalysisIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while performing the analysis.
        ///Error message:
        ///.
        /// </summary>
        public static string EssayExerciseViewAnalyzeTextExceptionErrorGeneric {
            get {
                return ResourceManager.GetString("EssayExerciseViewAnalyzeTextExceptionErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is too long to be submitted. The maximum number of words for this exercise is {0} (your text has {1} words)..
        /// </summary>
        public static string EssayExerciseViewAnalyzeTextExceptionTextTooLongForSubmission {
            get {
                return ResourceManager.GetString("EssayExerciseViewAnalyzeTextExceptionTextTooLongForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is too short to be analyzed. The minimum number of words is {0} (your text has {1} words)..
        /// </summary>
        public static string EssayExerciseViewAnalyzeTextExceptionTextTooShort {
            get {
                return ResourceManager.GetString("EssayExerciseViewAnalyzeTextExceptionTextTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is too short to be submitted. The minimum number of words for this exercise is {0} (your text has {1} words)..
        /// </summary>
        public static string EssayExerciseViewAnalyzeTextExceptionTextTooShortForSubmission {
            get {
                return ResourceManager.GetString("EssayExerciseViewAnalyzeTextExceptionTextTooShortForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        public static string EssayExerciseViewCountLabelText {
            get {
                return ResourceManager.GetString("EssayExerciseViewCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned exercise type is not supported yet.
        /// </summary>
        public static string EssayExerciseViewExerciseTypeNotSupported {
            get {
                return ResourceManager.GetString("EssayExerciseViewExerciseTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the exercise in the database..
        /// </summary>
        public static string EssayExerciseViewSaveExceptionAPI {
            get {
                return ResourceManager.GetString("EssayExerciseViewSaveExceptionAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis aborted.
        /// </summary>
        public static string EssayExerciseViewSaveExceptionOpCanceled {
            get {
                return ResourceManager.GetString("EssayExerciseViewSaveExceptionOpCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception..
        /// </summary>
        public static string EssayExerciseViewSaveExceptionUnknown {
            get {
                return ResourceManager.GetString("EssayExerciseViewSaveExceptionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EssayExerciseView supports only string content at this time.
        /// </summary>
        public static string EssayExerciseViewStringContentError {
            get {
                return ResourceManager.GetString("EssayExerciseViewStringContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary search.
        /// </summary>
        public static string Exercise_DictionarySearchName {
            get {
                return ResourceManager.GetString("Exercise_DictionarySearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essay.
        /// </summary>
        public static string Exercise_EssayName {
            get {
                return ResourceManager.GetString("Exercise_EssayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise specifications.
        /// </summary>
        public static string Exercise_ExerciseSpecifications {
            get {
                return ResourceManager.GetString("Exercise_ExerciseSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Exercise_ExerciseSpecificationsText_WithoutReferenceText {
            get {
                return ResourceManager.GetString("Exercise_ExerciseSpecificationsText_WithoutReferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Reference text:
        ///{1}.
        /// </summary>
        public static string Exercise_ExerciseSpecificationsText_WithReferenceText {
            get {
                return ResourceManager.GetString("Exercise_ExerciseSpecificationsText_WithReferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string Exercise_GenericName {
            get {
                return ResourceManager.GetString("Exercise_GenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display the chosen exercise..
        /// </summary>
        public static string Exercise_UnableToDisplay {
            get {
                return ResourceManager.GetString("Exercise_UnableToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different words (types).
        /// </summary>
        public static string ExerciseAnalysis_DifferentWords {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_DifferentWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is empty..
        /// </summary>
        public static string ExerciseAnalysis_EmptyPoSList {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_EmptyPoSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Explore your text.
        /// </summary>
        public static string ExerciseAnalysis_ExploreText_Contracted {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ExploreText_Contracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Explore your text.
        /// </summary>
        public static string ExerciseAnalysis_ExploreText_Expanded {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ExploreText_Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string ExerciseAnalysis_Families {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-frequency distribution.
        /// </summary>
        public static string ExerciseAnalysis_KFrequencyDistribution {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_KFrequencyDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of words in this category.
        /// </summary>
        public static string ExerciseAnalysis_ListOfWordsInThisCategory {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ListOfWordsInThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertaining to onlist only.
        /// </summary>
        public static string ExerciseAnalysis_PertainingOnlistOnly {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_PertainingOnlistOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertaining to the whole text.
        /// </summary>
        public static string ExerciseAnalysis_PertainingWholeText {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_PertainingWholeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Profile levels.
        /// </summary>
        public static string ExerciseAnalysis_ProfileLevelTitle_Contracted {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ProfileLevelTitle_Contracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Profile levels.
        /// </summary>
        public static string ExerciseAnalysis_ProfileLevelTitle_Expanded {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ProfileLevelTitle_Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ExerciseAnalysis_Refresh {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Related ratios and indices.
        /// </summary>
        public static string ExerciseAnalysis_RelatedRatiosIndices_Contracted {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_RelatedRatiosIndices_Contracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Related ratios and indices.
        /// </summary>
        public static string ExerciseAnalysis_RelatedRatiosIndices_Expanded {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_RelatedRatiosIndices_Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} ({2}).
        /// </summary>
        public static string ExerciseAnalysis_Subtitle {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExerciseAnalysis_Title {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        public static string ExerciseAnalysis_Tokens {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens per family.
        /// </summary>
        public static string ExerciseAnalysis_TokensPerFamily {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TokensPerFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens per type.
        /// </summary>
        public static string ExerciseAnalysis_TokensPerType {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TokensPerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string ExerciseAnalysis_Types {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types per family.
        /// </summary>
        public static string ExerciseAnalysis_TypesPerFamily {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TypesPerFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type-token ratio.
        /// </summary>
        public static string ExerciseAnalysis_TypeTokenRatio {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TypeTokenRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words in text (tokens).
        /// </summary>
        public static string ExerciseAnalysis_WordsInText {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_WordsInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of words for this part of speech:.
        /// </summary>
        public static string ExerciseAnalysis_WordsPerPoS {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_WordsPerPoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string GenericCloseSymbol {
            get {
                return ResourceManager.GetString("GenericCloseSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string GenericOpenSymbol {
            get {
                return ResourceManager.GetString("GenericOpenSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Internet connection is required to use Tell-OP. Please connect and try again..
        /// </summary>
        public static string InternetConnectionRequiredError {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection required.
        /// </summary>
        public static string InternetConnectionRequiredErrorTitle {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Language_Italian {
            get {
                return ResourceManager.GetString("Language_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. English.
        /// </summary>
        public static string Language_USEnglish {
            get {
                return ResourceManager.GetString("Language_USEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1 level (breakthrough).
        /// </summary>
        public static string LanguageLevel_A1_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_A1_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        public static string LanguageLevel_A1_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_A1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2 level (waystage).
        /// </summary>
        public static string LanguageLevel_A2_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_A2_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        public static string LanguageLevel_A2_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_A2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1 level (threshold).
        /// </summary>
        public static string LanguageLevel_B1_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_B1_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1.
        /// </summary>
        public static string LanguageLevel_B1_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_B1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2 level (vantage).
        /// </summary>
        public static string LanguageLevel_B2_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_B2_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2.
        /// </summary>
        public static string LanguageLevel_B2_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_B2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1 level (effective operational proficiency).
        /// </summary>
        public static string LanguageLevel_C1_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_C1_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        public static string LanguageLevel_C1_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_C1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2 level (mastery).
        /// </summary>
        public static string LanguageLevel_C2_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_C2_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        public static string LanguageLevel_C2_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_C2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown level.
        /// </summary>
        public static string LanguageLevel_Unknown_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_Unknown_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkn..
        /// </summary>
        public static string LanguageLevel_Unknown_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_Unknown_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Login_AboutLabel {
            get {
                return ResourceManager.GetString("Login_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...or....
        /// </summary>
        public static string Login_Or {
            get {
                return ResourceManager.GetString("Login_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Login_PrivacyLabel {
            get {
                return ResourceManager.GetString("Login_PrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new account.
        /// </summary>
        public static string Login_RegisterButton {
            get {
                return ResourceManager.GetString("Login_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_SignUpLabel {
            get {
                return ResourceManager.GetString("Login_SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word to search for.
        /// </summary>
        public static string MainSearch_EnterTerm {
            get {
                return ResourceManager.GetString("MainSearch_EnterTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on the buttons below to show/hide definitions and search results..
        /// </summary>
        public static string MainSearch_HowTo {
            get {
                return ResourceManager.GetString("MainSearch_HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of words that appears after &quot;{0}&quot;..
        /// </summary>
        public static string MainSearch_StringNet_CollocationsAfterTitle {
            get {
                return ResourceManager.GetString("MainSearch_StringNet_CollocationsAfterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of words that appears before &quot;{0}&quot;..
        /// </summary>
        public static string MainSearch_StringNet_CollocationsBeforeTitle {
            get {
                return ResourceManager.GetString("MainSearch_StringNet_CollocationsBeforeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MainSearch_Title {
            get {
                return ResourceManager.GetString("MainSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of following words.
        /// </summary>
        public static string NetSpeak_Following {
            get {
                return ResourceManager.GetString("NetSpeak_Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of preceding words.
        /// </summary>
        public static string NetSpeak_Preceding {
            get {
                return ResourceManager.GetString("NetSpeak_Preceding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to log you in. Please try again..
        /// </summary>
        public static string OAuth2_AuthenticationCompleteNotAuthenticatedError {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationCompleteNotAuthenticatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        public static string OAuth2_AuthenticationCompleteNotAuthenticatedErrorTitle {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationCompleteNotAuthenticatedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication process did not complete successfully. Please try again..
        /// </summary>
        public static string OAuth2_AuthenticationError {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        public static string OAuth2_AuthenticationErrorTitle {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to authenticating you. Please try again..
        /// </summary>
        public static string OAuth2_RequestTokenError {
            get {
                return ResourceManager.GetString("OAuth2_RequestTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        public static string OAuth2_RequestTokenErrorTitle {
            get {
                return ResourceManager.GetString("OAuth2_RequestTokenErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Tell-OP.
        /// </summary>
        public static string OAuth2_Title {
            get {
                return ResourceManager.GetString("OAuth2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjective.
        /// </summary>
        public static string PartOfSpeech_Adjective {
            get {
                return ResourceManager.GetString("PartOfSpeech_Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverb.
        /// </summary>
        public static string PartOfSpeech_Adverb {
            get {
                return ResourceManager.GetString("PartOfSpeech_Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary verb.
        /// </summary>
        public static string PartOfSpeech_AuxiliaryVerb {
            get {
                return ResourceManager.GetString("PartOfSpeech_AuxiliaryVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinal number.
        /// </summary>
        public static string PartOfSpeech_CardinalNumber {
            get {
                return ResourceManager.GetString("PartOfSpeech_CardinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clause opener.
        /// </summary>
        public static string PartOfSpeech_ClauseOpener {
            get {
                return ResourceManager.GetString("PartOfSpeech_ClauseOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common noun.
        /// </summary>
        public static string PartOfSpeech_CommonNoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_CommonNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjunction.
        /// </summary>
        public static string PartOfSpeech_Conjunction {
            get {
                return ResourceManager.GetString("PartOfSpeech_Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determiner.
        /// </summary>
        public static string PartOfSpeech_Determiner {
            get {
                return ResourceManager.GetString("PartOfSpeech_Determiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determiner/Pronoun.
        /// </summary>
        public static string PartOfSpeech_Determiner_Pronoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_Determiner_Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclamation.
        /// </summary>
        public static string PartOfSpeech_Exclamation {
            get {
                return ResourceManager.GetString("PartOfSpeech_Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existential particle.
        /// </summary>
        public static string PartOfSpeech_ExistentialParticle {
            get {
                return ResourceManager.GetString("PartOfSpeech_ExistentialParticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign word.
        /// </summary>
        public static string PartOfSpeech_ForeignWord {
            get {
                return ResourceManager.GetString("PartOfSpeech_ForeignWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genitive.
        /// </summary>
        public static string PartOfSpeech_Genitive {
            get {
                return ResourceManager.GetString("PartOfSpeech_Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinitive marker.
        /// </summary>
        public static string PartOfSpeech_InfinitiveMarker {
            get {
                return ResourceManager.GetString("PartOfSpeech_InfinitiveMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interjection or discourse marker.
        /// </summary>
        public static string PartOfSpeech_Interjection {
            get {
                return ResourceManager.GetString("PartOfSpeech_Interjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter of the alphabet treated as a word.
        /// </summary>
        public static string PartOfSpeech_LetterAsWord {
            get {
                return ResourceManager.GetString("PartOfSpeech_LetterAsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal verb.
        /// </summary>
        public static string PartOfSpeech_ModalVerb {
            get {
                return ResourceManager.GetString("PartOfSpeech_ModalVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative marker.
        /// </summary>
        public static string PartOfSpeech_NegativeMarker {
            get {
                return ResourceManager.GetString("PartOfSpeech_NegativeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        public static string PartOfSpeech_Ordinal {
            get {
                return ResourceManager.GetString("PartOfSpeech_Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of a proper noun (United Kingdom, Los Angeles, New Zealand...).
        /// </summary>
        public static string PartOfSpeech_PartProperNoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_PartProperNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preposition.
        /// </summary>
        public static string PartOfSpeech_Preposition {
            get {
                return ResourceManager.GetString("PartOfSpeech_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronoun.
        /// </summary>
        public static string PartOfSpeech_Pronoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper noun.
        /// </summary>
        public static string PartOfSpeech_ProperNoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_ProperNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified.
        /// </summary>
        public static string PartOfSpeech_Unclassified {
            get {
                return ResourceManager.GetString("PartOfSpeech_Unclassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized term.
        /// </summary>
        public static string PartOfSpeech_Unrecognized {
            get {
                return ResourceManager.GetString("PartOfSpeech_Unrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb.
        /// </summary>
        public static string PartOfSpeech_Verb {
            get {
                return ResourceManager.GetString("PartOfSpeech_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname.
        /// </summary>
        public static string Profile_DisplayName {
            get {
                return ResourceManager.GetString("Profile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language level.
        /// </summary>
        public static string Profile_LanguageLevel {
            get {
                return ResourceManager.GetString("Profile_LanguageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a search term in the search bar..
        /// </summary>
        public static string Search_NoTermEntered_Text {
            get {
                return ResourceManager.GetString("Search_NoTermEntered_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search term entered.
        /// </summary>
        public static string Search_NoTermEntered_Title {
            get {
                return ResourceManager.GetString("Search_NoTermEntered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the search results. Please try again..
        /// </summary>
        public static string Search_TabError {
            get {
                return ResourceManager.GetString("Search_TabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collins.
        /// </summary>
        public static string SingleWordExploration_Collins {
            get {
                return ResourceManager.GetString("SingleWordExploration_Collins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collins Definitions.
        /// </summary>
        public static string SingleWordExploration_CollinsDefinitionsTitle {
            get {
                return ResourceManager.GetString("SingleWordExploration_CollinsDefinitionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string SingleWordExploration_Definitions {
            get {
                return ResourceManager.GetString("SingleWordExploration_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetSpeak.
        /// </summary>
        public static string SingleWordExploration_NetSpeak {
            get {
                return ResourceManager.GetString("SingleWordExploration_NetSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stands4.
        /// </summary>
        public static string SingleWordExploration_Stands4 {
            get {
                return ResourceManager.GetString("SingleWordExploration_Stands4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stands4 Definitions.
        /// </summary>
        public static string SingleWordExploration_Stands4DefinitionsTitle {
            get {
                return ResourceManager.GetString("SingleWordExploration_Stands4DefinitionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collocations.
        /// </summary>
        public static string SingleWordExploration_StringNet {
            get {
                return ResourceManager.GetString("SingleWordExploration_StringNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antonyms.
        /// </summary>
        public static string Stands4ViewCell_Antonyms {
            get {
                return ResourceManager.GetString("Stands4ViewCell_Antonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        public static string Stands4ViewCell_Definition {
            get {
                return ResourceManager.GetString("Stands4ViewCell_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Stands4.
        /// </summary>
        public static string Stands4ViewCell_DictionaryName_Contracted {
            get {
                return ResourceManager.GetString("Stands4ViewCell_DictionaryName_Contracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Stands4.
        /// </summary>
        public static string Stands4ViewCell_DictionaryName_Expanded {
            get {
                return ResourceManager.GetString("Stands4ViewCell_DictionaryName_Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Stands4ViewCell_Example {
            get {
                return ResourceManager.GetString("Stands4ViewCell_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        public static string Stands4ViewCell_Synonyms {
            get {
                return ResourceManager.GetString("Stands4ViewCell_Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collocation.
        /// </summary>
        public static string StringNetViewCell_Collocation {
            get {
                return ResourceManager.GetString("StringNetViewCell_Collocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string StringNetViewCell_Contracted {
            get {
                return ResourceManager.GetString("StringNetViewCell_Contracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string StringNetViewCell_Example {
            get {
                return ResourceManager.GetString("StringNetViewCell_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string StringNetViewCell_Expanded {
            get {
                return ResourceManager.GetString("StringNetViewCell_Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string StringNetViewCell_Frequency {
            get {
                return ResourceManager.GetString("StringNetViewCell_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        ///
        ///Please contact the developers, telling them the exact steps you performed in the application, so that they will be able to fix it..
        /// </summary>
        public static string UnexpectedException_Text {
            get {
                return ResourceManager.GetString("UnexpectedException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string UnexpectedException_Title {
            get {
                return ResourceManager.GetString("UnexpectedException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        ///
        ///Please contact the developers, telling them the exact steps you performed in the application, so that they will be able to fix it.
        ///
        ///Error details: {0}.
        /// </summary>
        public static string UnexpectedException_WithDetails_Text {
            get {
                return ResourceManager.GetString("UnexpectedException_WithDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save and override the previous content?.
        /// </summary>
        public static string UserMessageSaveAndOverrideQuestion {
            get {
                return ResourceManager.GetString("UserMessageSaveAndOverrideQuestion", resourceCulture);
            }
        }
    }
}
