//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TellOP.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TellOP.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred while retrieving your profile data from the server. Please try again..
        /// </summary>
        public static string API_UserDataError {
            get {
                return ResourceManager.GetString("API_UserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile data retrieval error.
        /// </summary>
        public static string API_UserDataErrorTitle {
            get {
                return ResourceManager.GetString("API_UserDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred while reading your profile data retrieved from the server. Please try again..
        /// </summary>
        public static string API_UserDataJSONError {
            get {
                return ResourceManager.GetString("API_UserDataJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile data retrieval error.
        /// </summary>
        public static string API_UserDataJSONErrorTitle {
            get {
                return ResourceManager.GetString("API_UserDataJSONErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copyright © 2016 University of Murcia
        ///
        ///Developed by Mattia Zago and Alessandro Menti.
        /// </summary>
        public static string AppCredits {
            get {
                return ResourceManager.GetString("AppCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tell-OP.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile.
        /// </summary>
        public static string ButtonProfile {
            get {
                return ResourceManager.GetString("ButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refresh.
        /// </summary>
        public static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Definitions:
        ///{0}.
        /// </summary>
        public static string CollinsWord_DefinitionTemplate {
            get {
                return ResourceManager.GetString("CollinsWord_DefinitionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Examples:
        ///{0}.
        /// </summary>
        public static string CollinsWord_ExamplesTemplate {
            get {
                return ResourceManager.GetString("CollinsWord_ExamplesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Related:
        ///{0}.
        /// </summary>
        public static string CollinsWord_RelatedTemplate {
            get {
                return ResourceManager.GetString("CollinsWord_RelatedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a See also:
        ///{0}.
        /// </summary>
        public static string CollinsWord_SeeAlsoTemplate {
            get {
                return ResourceManager.GetString("CollinsWord_SeeAlsoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sense {0}:
        ///.
        /// </summary>
        public static string CollinsWord_SenseCounter {
            get {
                return ResourceManager.GetString("CollinsWord_SenseCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Featured.
        /// </summary>
        public static string Dashboard_TabFeatured {
            get {
                return ResourceManager.GetString("Dashboard_TabFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a History.
        /// </summary>
        public static string Dashboard_TabHistory {
            get {
                return ResourceManager.GetString("Dashboard_TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stats.
        /// </summary>
        public static string Dashboard_TabStats {
            get {
                return ResourceManager.GetString("Dashboard_TabStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dashboard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Write an essay between {0} and {1} words..
        /// </summary>
        public static string EssayExercise_MinMaxWords {
            get {
                return ResourceManager.GetString("EssayExercise_MinMaxWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Essay.
        /// </summary>
        public static string Exercise_EssayName {
            get {
                return ResourceManager.GetString("Exercise_EssayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exercise.
        /// </summary>
        public static string Exercise_GenericName {
            get {
                return ResourceManager.GetString("Exercise_GenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Different words (types).
        /// </summary>
        public static string ExerciseAnalysis_DifferentWords {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_DifferentWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Explore your text.
        /// </summary>
        public static string ExerciseAnalysis_ExploreText {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ExploreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Families.
        /// </summary>
        public static string ExerciseAnalysis_Families {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a K-Frequency distribution.
        /// </summary>
        public static string ExerciseAnalysis_KFrequencyDistribution {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_KFrequencyDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pertaining to onlist only.
        /// </summary>
        public static string ExerciseAnalysis_PertainingOnlistOnly {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_PertainingOnlistOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pertaining to the whole text.
        /// </summary>
        public static string ExerciseAnalysis_PertainingWholeText {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_PertainingWholeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile Levels.
        /// </summary>
        public static string ExerciseAnalysis_ProfileLevelTitle {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_ProfileLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Related Ratios and Indices.
        /// </summary>
        public static string ExerciseAnalysis_RelatedRatiosIndices {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_RelatedRatiosIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tokens.
        /// </summary>
        public static string ExerciseAnalysis_Tokens {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tokens per Family.
        /// </summary>
        public static string ExerciseAnalysis_TokensPerFamily {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TokensPerFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tokens per type.
        /// </summary>
        public static string ExerciseAnalysis_TokensPerType {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TokensPerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Types.
        /// </summary>
        public static string ExerciseAnalysis_Types {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Types per Family.
        /// </summary>
        public static string ExerciseAnalysis_TypesPerFamily {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TypesPerFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type-token ratio.
        /// </summary>
        public static string ExerciseAnalysis_TypeTokenRatio {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_TypeTokenRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Words in text (tokens).
        /// </summary>
        public static string ExerciseAnalysis_WordsInText {
            get {
                return ResourceManager.GetString("ExerciseAnalysis_WordsInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An Internet connection is required to use Tell-OP. Please connect and try again..
        /// </summary>
        public static string InternetConnectionRequiredError {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Internet connection required.
        /// </summary>
        public static string InternetConnectionRequiredErrorTitle {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A1 level (breakthrough).
        /// </summary>
        public static string LanguageLevel_A1_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_A1_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A1.
        /// </summary>
        public static string LanguageLevel_A1_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_A1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A2 level (waystage).
        /// </summary>
        public static string LanguageLevel_A2_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_A2_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A2.
        /// </summary>
        public static string LanguageLevel_A2_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_A2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B1 level (threshold).
        /// </summary>
        public static string LanguageLevel_B1_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_B1_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B1.
        /// </summary>
        public static string LanguageLevel_B1_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_B1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B2 level (vantage).
        /// </summary>
        public static string LanguageLevel_B2_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_B2_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B2.
        /// </summary>
        public static string LanguageLevel_B2_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_B2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C1 level (effective operational proficiency).
        /// </summary>
        public static string LanguageLevel_C1_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_C1_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C1.
        /// </summary>
        public static string LanguageLevel_C1_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_C1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C2 level (mastery).
        /// </summary>
        public static string LanguageLevel_C2_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_C2_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C2.
        /// </summary>
        public static string LanguageLevel_C2_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_C2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown level.
        /// </summary>
        public static string LanguageLevel_Unknown_Long {
            get {
                return ResourceManager.GetString("LanguageLevel_Unknown_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        public static string LanguageLevel_Unknown_Short {
            get {
                return ResourceManager.GetString("LanguageLevel_Unknown_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        public static string Login_AboutLabel {
            get {
                return ResourceManager.GetString("Login_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log in.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privacy.
        /// </summary>
        public static string Login_PrivacyLabel {
            get {
                return ResourceManager.GetString("Login_PrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Register a new account.
        /// </summary>
        public static string Login_RegisterButton {
            get {
                return ResourceManager.GetString("Login_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign Up.
        /// </summary>
        public static string Login_SignUpLabel {
            get {
                return ResourceManager.GetString("Login_SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred while trying to log you in. Please try again..
        /// </summary>
        public static string OAuth2_AuthenticationCompleteNotAuthenticatedError {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationCompleteNotAuthenticatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login error.
        /// </summary>
        public static string OAuth2_AuthenticationCompleteNotAuthenticatedErrorTitle {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationCompleteNotAuthenticatedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The authentication process did not complete successfully. Please try again..
        /// </summary>
        public static string OAuth2_AuthenticationError {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login error.
        /// </summary>
        public static string OAuth2_AuthenticationErrorTitle {
            get {
                return ResourceManager.GetString("OAuth2_AuthenticationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred while trying to authenticating you. Please try again..
        /// </summary>
        public static string OAuth2_RequestTokenError {
            get {
                return ResourceManager.GetString("OAuth2_RequestTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login error.
        /// </summary>
        public static string OAuth2_RequestTokenErrorTitle {
            get {
                return ResourceManager.GetString("OAuth2_RequestTokenErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login to Tell-OP.
        /// </summary>
        public static string OAuth2_Title {
            get {
                return ResourceManager.GetString("OAuth2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adjective.
        /// </summary>
        public static string PartOfSpeech_Adjective {
            get {
                return ResourceManager.GetString("PartOfSpeech_Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adverb.
        /// </summary>
        public static string PartOfSpeech_Adverb {
            get {
                return ResourceManager.GetString("PartOfSpeech_Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cardinal Number.
        /// </summary>
        public static string PartOfSpeech_CardinalNumber {
            get {
                return ResourceManager.GetString("PartOfSpeech_CardinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clause Opener.
        /// </summary>
        public static string PartOfSpeech_ClauseOpener {
            get {
                return ResourceManager.GetString("PartOfSpeech_ClauseOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Common Noun.
        /// </summary>
        public static string PartOfSpeech_CommonNoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_CommonNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conjunction.
        /// </summary>
        public static string PartOfSpeech_Conjunction {
            get {
                return ResourceManager.GetString("PartOfSpeech_Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Determiner.
        /// </summary>
        public static string PartOfSpeech_Determiner {
            get {
                return ResourceManager.GetString("PartOfSpeech_Determiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Determiner/Pronoun.
        /// </summary>
        public static string PartOfSpeech_Determiner_Pronoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_Determiner_Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Existential Particle.
        /// </summary>
        public static string PartOfSpeech_ExistentialParticle {
            get {
                return ResourceManager.GetString("PartOfSpeech_ExistentialParticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Foreign Word.
        /// </summary>
        public static string PartOfSpeech_ForeignWord {
            get {
                return ResourceManager.GetString("PartOfSpeech_ForeignWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genitive.
        /// </summary>
        public static string PartOfSpeech_Genitive {
            get {
                return ResourceManager.GetString("PartOfSpeech_Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Infinitive Marker.
        /// </summary>
        public static string PartOfSpeech_InfinitiveMarker {
            get {
                return ResourceManager.GetString("PartOfSpeech_InfinitiveMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Interjection or Discourse Marker.
        /// </summary>
        public static string PartOfSpeech_Interjection {
            get {
                return ResourceManager.GetString("PartOfSpeech_Interjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Letter of the alphabet treated as a word.
        /// </summary>
        public static string PartOfSpeech_LetterAsWord {
            get {
                return ResourceManager.GetString("PartOfSpeech_LetterAsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modal Verb.
        /// </summary>
        public static string PartOfSpeech_ModalVerb {
            get {
                return ResourceManager.GetString("PartOfSpeech_ModalVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negative Marker.
        /// </summary>
        public static string PartOfSpeech_NegativeMarker {
            get {
                return ResourceManager.GetString("PartOfSpeech_NegativeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordinal.
        /// </summary>
        public static string PartOfSpeech_Ordinal {
            get {
                return ResourceManager.GetString("PartOfSpeech_Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Part of a proper Noun (United Kingdom, Los Angeles, New Zealand, ...).
        /// </summary>
        public static string PartOfSpeech_PartProperNoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_PartProperNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preposition.
        /// </summary>
        public static string PartOfSpeech_Preposition {
            get {
                return ResourceManager.GetString("PartOfSpeech_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pronoun.
        /// </summary>
        public static string PartOfSpeech_Pronoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proper Noun.
        /// </summary>
        public static string PartOfSpeech_ProperNoun {
            get {
                return ResourceManager.GetString("PartOfSpeech_ProperNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unclassified.
        /// </summary>
        public static string PartOfSpeech_Unclassified {
            get {
                return ResourceManager.GetString("PartOfSpeech_Unclassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unrecognized Term.
        /// </summary>
        public static string PartOfSpeech_Unrecognized {
            get {
                return ResourceManager.GetString("PartOfSpeech_Unrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verb.
        /// </summary>
        public static string PartOfSpeech_Verb {
            get {
                return ResourceManager.GetString("PartOfSpeech_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name and surname.
        /// </summary>
        public static string Profile_DisplayName {
            get {
                return ResourceManager.GetString("Profile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E-mail address.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language level.
        /// </summary>
        public static string Profile_LanguageLevel {
            get {
                return ResourceManager.GetString("Profile_LanguageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
    }
}
